var bulb=0,lock=1,sound=1,eye=1,oetime=null,imr=1,stickyScroll=1,refresh=1,delay,sub=0,ericreset=1,normreset=1,integ=false,hscroll='',jqclicked=false,dt=null,st=null,eye=true,syntax = "&lt;!DOCTYPE html&gt;<br/>&lt;html&gt;<br/>&lt;head&gt;<br/>&lt;title&gt&lt;!-- title --&gt;&lt;/title&gt;<br/> &lt;/head&gt;<br/> &lt;body&gt;<br/> &lt;!-- your content here --&gt;<br/> &lt;/body&gt;<br/>&lt;/html&gt;",
  marquee='<marquee behavior="scroll" id="marquee" scrollamount="3" direction="left" width="100%"></marquee>',
  base="<!DOCTYPE html>\n" +"<html>\n" +"<head>\n" +"<meta charset=\"utf-8\">\n" +"</head>\n" +"<body>\n" +"</body>\n" +"</html>",
  mod='<div id="modal"><p id="title"></p><div id="modalinner"></div></div>',cancel='<i id="cancel" class="icon remove"> Close</i>',
  eric="/* CSS RESET STARTED */"+"\n"+"html, body, div, span, applet, object, iframe,h1, h2, h3, h4, h5, h6, p, blockquote, pre,a, abbr, acronym, address, big, cite, code,del, dfn, em, img, ins, kbd, q, s, samp,small, strike, strong, sub, sup, tt, var,b, u, i, center,dl, dt, dd, ol, ul, li,fieldset, form, label, legend,table, caption, tbody, tfoot, thead, tr, th, td,article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup,menu, nav, output, ruby, section, summary,time, mark, audio, video {margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;}"+"\n"+"article, aside, details, figcaption, figure, footer, header, hgroup, menu, nav, section {display: block;}"+"\n"+"body {line-height: 1;}"+"\n"+"ol, ul {list-style: none;}"+"\n"+"blockquote, q {quotes: none;}"+"\n"+"blockquote:before, blockquote:after,q:before, q:after {content: '';content: none;}"+"\n"+"table {border-collapse: collapse;border-spacing: 0;}"+"\n"+"/* CSS RESET FINISHED */",
  normalize = "/* NORMALIZE CSS START */"+"\n"+"article,aside,details,figcaption,figure,footer,header,hgroup,main,nav,section,summary{display:block;}"+"\n"+"audio,canvas,video{display:inline-block;*display:inline;*zoom:1;}"+"\n"+"audio:not([controls]){display:none;height:0;}"+"\n"+"[hidden]{display:none;}"+"\n"+"html{font-size:100%;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;}"+"\n"+"html,button,input,select,textarea{font-family:sans-serif;}"+"\n"+"body{margin:0;}"+"\n"+"a:focus{outline:thin dotted;}"+"\n"+"a:active,a:hover{outline:0;}"+"\n"+"h1{font-size:2em;margin:0.67em 0;}"+"\n"+"h2{font-size:1.5em;margin:0.83em 0;}"+"\n"+"h3{font-size:1.17em;margin:1em 0;}"+"\n"+"h4{font-size:1em;margin:1.33em 0;}"+"\n"+"h5{font-size:0.83em;margin:1.67em 0;}"+"\n"+"h6{font-size:0.67em;margin:2.33em 0;}"+"\n"+"abbr[title]{border-bottom:1px dotted;}"+"\n"+"b,strong{font-weight:bold;}"+"\n"+"blockquote{margin:1em 40px;}"+"\n"+"dfn{font-style:italic;}"+"\n"+"hr{-moz-box-sizing:content-box;box-sizing:content-box;height:0;}"+"\n"+"mark{background:#ff0;color:#000;}"+"\n"+"p,pre{margin:1em 0;}"+"\n"+"code,kbd,pre,samp{font-family:monospace,serif;_font-family:'courier new',monospace;font-size:1em;}"+"\n"+"pre{white-space:pre;white-space:pre-wrap;word-wrap:break-word;}"+"\n"+"q{quotes:none;}"+"\n"+"q:before,q:after{content:'';content:none;}"+"\n"+"small{font-size:80%;}"+"\n"+"sub,sup{font-size:75%;line-height:0;position:relative;vertical-align:baseline;}"+"\n"+"sup{top:-0.5em;}"+"\n"+"sub{bottom:-0.25em;}"+"\n"+"dl,menu,ol,ul{margin:1em 0;}"+"\n"+"dd{margin:0 0 0 40px;}"+"\n"+"menu,ol,ul{padding:0 0 0 40px;}"+"\n"+"nav ul,nav ol{list-style:none;list-style-image:none;}"+"\n"+"img{border:0;-ms-interpolation-mode:bicubic;}"+"\n"+"svg:not(:root){overflow:hidden;}"+"\n"+"figure{margin:0;}"+"\n"+"form{margin:0;}"+"\n"+"fieldset{border:1px solid #c0c0c0;margin:0 2px;padding:0.35em 0.625em 0.75em;}"+"\n"+"legend{border:0;padding:0;white-space:normal;*margin-left:-7px;}"+"\n"+"button,input,select,textarea{font-size:100%;margin:0;vertical-align:baseline;*vertical-align:middle;}"+"\n"+"button,input{line-height:normal;}"+"\n"+"button,select{text-transform:none;}"+"\n"+"button,html input[type='button'],input[type='reset'],input[type='submit']{-webkit-appearance:button;cursor:pointer;*overflow:visible;}"+"\n"+"button[disabled],html input[disabled]{cursor:default;}"+"\n"+"input[type='checkbox'],input[type='radio']{box-sizing:border-box;padding:0;*height:13px;*width:13px;}"+"\n"+"input[type='search']{-webkit-appearance:textfield;-moz-box-sizing:content-box;-webkit-box-sizing:content-box;box-sizing:content-box;}"+"\n"+"input[type='search']::-webkit-search-cancel-button,input[type='search']::-webkit-search-decoration{-webkit-appearance:none;}"+"\n"+"button::-moz-focus-inner,input::-moz-focus-inner{border:0;padding:0;}"+"\n"+"textarea{overflow:auto;vertical-align:top;}"+"\n"+"table{border-collapse:collapse;border-spacing:0;}"+"\n"+"/* NORMALIZE CSS FINISHED */",
  lib='<div id="libdiv"><ul></ul></div>',jssyntax='<script type="text/javascript" src=""></script>',
  jslib='<div class="jslib"><h4>A</h4><li data-url="files/angular.min.js">Angular JS</li><h4>B</h4><li data-url="files/backbone-min.js">Backbone JS</li><li data-url="files/bootstrap.js">Bootstrap</li><h4>C</h4><li data-url="files/createjs-2013.09.25.min.js">Create JS</li><li data-url="files/Chart.min.js">Chart JS</li><h4>D</h4><li data-url="files/d3.v3.min.js">D3</li><li data-url="files/dojo.js">Dojo</li><h4>E</h4><li data-url="files/ember.min.js">Ember</li><li data-url="files/enyo.js">Enyo JS</li><li data-url="files/ext-all.js">Ext JS</li><h4>F</h4><li data-url="files/fabric.min.js">Fabric JS</li><h4>J</h4><li data-url="files/jquery-latest.min.js">jQuery<span class="new">Popular!</span></li><li data-url="files/jquery-ui.min.js">jQuery UI</li><li data-url="files/jquery.mobile.js">jQuery Mobile</li><li data-url="files/jquery.tools.min.js">jQuery Tools</li><h4>K</h4><li data-url="files/kinetic-v4.7.3.min.js">Kinetic JS</li><li data-url="files/knockout-3.0.0.js">Knockout JS</li><h4>M</h4><li data-url="files/modernizr-latest.js">Modernizr</li><li data-url="files/mootools-yui-compressed.js">Moo Tools</li><h4>P</h4><li data-url="files/paper.js">Paper JS</li><li data-url="files/processing-1.4.1.min.js">Processing JS</li><li data-url="files/prototype.js">Prototype JS</li><h4>Q</h4><li data-url="files/q-3.0.1.min.js">Qooxdoo</li><li data-url="files/raphael-min.js">Raphael JS</li><h4>S</h4><li data-url="files/scriptaculous.js">Script.aculo.us</li><li data-url="files/snap.svg-min.js">Snap SVG</li><li data-url="files/svg.min.js">SVG JS</li><h4>T</h4><li data-url="files/three.min.js">Three JS</li><h4>U</h4><li data-url="files/underscore-min150.js">Underscore JS</li><h4>W</h4><li data-url="files/webfont.js">Web Font Loader</li><h4>Y</h4><li data-url="files/yui-min.js">YUI</li><h4>Z</h4><li data-url="files/zepto.min.js">Zepto</li></div>',
  metalib='<h4>For Mobile</h4><li id="metahandheld">Handheld Friendly</li><li id="metamob">Mobile Optimized</li><li id="metaviewport">Viewport</li><h4>APPLE</h4><li id="metafullscreen">Apple-touch-fullscreen</li><li id="metacapable">Apple-mobile-web-app-capable</li><li id="metastatus">Apple-mobile-web-app-status-bar-style</li><li id="metatitle">Apple-mobile-web-app-title</li><li id="metacontent">Content</li><li id="metacomp">X-UA-Compatible</li><li id="metacache">Cache-control</li><li id="metapragma">Pragma<span class="new">New!</span></li><li id="metades">Description</li><li id="metakeyword">Keywords</li><li id="metacopy">Copyright</li><li id="metaauthor">Author</li><li id="metadesigner">Designer</li><li id="metacat">Category</li><li id="metareply">Reply-to</li><li id="metaowner">Owner</li><li id="metaurl">URL</li><li id="metarevisit">Revisit after</li><li id="metaexpire">Expires</li>',
  csslib='<div class="csslib"><h4>0-9</h4><li data-url="files/1140grid.css">1140 Grid</li><li data-url="files/960grid.css">960 Grid</li><h4>B</h4><li data-url="files/base.css">Base</li><li data-url="files/blueprint.css">BluePrint</li><li data-url="files/bootstrap.css">Bootstrap</li><h4>C</h4><li data-url="files/compass.css">Compass</li><li data-url="files/columnal.css">Columnal</li><h4>F</h4><li data-url="files/fluidbaselinegrid.css">Fluid BaseLine Grid</li><li data-url="files/foundation3.css">Foundation3</li><h4>G</h4><li data-url="files/goldengrid.css">Golden Grid</li><li data-url="files/goldilocks.css">GoldiLocks</li><li data-url="files/gridless.css">GridLess</li><li data-url="files/gridiculo.css">Gridiculo</li><li data-url="files/gumby.css">Gumby</li><li data-url="files/groundwork.css">GroundWork</li><h4>I</h4><li data-url="files/inuitcss.css">IncuitCSS</li><li data-url="files/ingrid.css">Ingrid</li><h4>J</h4><li data-url="files/jquery-mobile.css">jQuery Mobile</li><li data-url="files/jquery-ui.css">jQuery UI</li><h4>K</h4><li data-url="files/kube.css">Kube</li><h4>L</h4><li data-url="files/less4.css">Less4</li><h4>M</h4><li data-url="files/muellergrid.css">Muller Grid</li><h4>P</h4><li data-url="files/pure-min.css">Pure</li><li data-url="files/profound.css">Profound</li><h4>R</h4><li data-url="files/responsive.css">Responsive</li><li data-url="files/responsiveaeon.css">Responsive Aeon</li><li data-url="files/responsivegridsystem.css">Responsive Grid System</li><h4>S</h4><li data-url="files/semanticgridsystem.css">Semantic Grid System</li><li data-url="files/skeleton.css">Skeleton</li><li data-url="files/susy.css">Susy</li><h4>T</h4><li data-url="files/titan.css">Titan</li><li data-url="files/toast.css">Toast</li><li data-url="files/tuktuk.css">TukTuk</li><h4>Y</h4><li data-url="files/yaml4.css">YAML4</li></div>',
  csssyntax='<link href="" type="text/css" rel="stylesheet" />',
  ielib='<h4>IE</h4><li id="allie">All IE</li><li id="iel6">< IE6</li><li id="ie6">IE6</li><li id="ieg6">> IE6</li><li id="ie7">IE7</li><li id="iel8">< IE8</li><li id="ie8">IE8</li><li id="ieg8">> IE8</li><li id="iel9">< IE9</li><li id="ie9">IE9</li><li id="ieg9">> IE9</li><li id="iel10">< IE10</li><li id="ie10">IE10</li><li id="ieg10">> IE10</li>',
  close='<em class="close icon remove"></em>',
  lockdiv='<div id="lockdiv"><div><input type="password" id="unlockcode" placeholder="Enter Code" /><input type="button" value="Unlock" id="unlock" onclick="unlock();" /></div></div>';
	  
var htmlEditor = CodeMirror.fromTextArea(document.getElementById("htmlarea"),{
  mode:"pophtmlmixed",profile:'xhtml',lineNumbers:true,lineWrapping:true,dragDrop:true,matchBrackets:true,styleActiveLine:true,
  onChange: function(){if(refresh==1){clearTimeout(delay);delay=setTimeout(updateResult,300);}},
  extraKeys: { Tab: betterTab }
});
var htmlCompletion = new CodeCompletion(htmlEditor, new HtmlCompletion());
htmlEditor.setOption("onKeyEvent", function(cm, e) {return htmlCompletion.handleKeyEvent(cm, e);});

var cmthemesel = document.getElementById("cmtheme");
//function selectTheme(){var prvcmtheme=htmlEditor.getOption("theme"),nt,ot,h=document.getElementsByTagName('head')[0];var theme = cmthemesel.options[cmthemesel.selectedIndex].innerHTML;ot = document.getElementsByTagName('link');for(var k=ot.length;k>=0;k--){if(ot[k] && ot[k].getAttribute('href')!==null && ot[k].getAttribute('href').indexOf('mine/theme/'+prvcmtheme+'.css')!=-1){ot[k].parentNode.removeChild(ot[k]);}}nt = document.createElement("link");nt.setAttribute("rel","stylesheet");nt.setAttribute("type","text/css");nt.setAttribute("href",'mine/theme/'+theme+'.css');if(typeof nt!="undefined"){h.appendChild(nt);}htmlEditor.setOption("theme", theme);cssEditor.setOption("theme", theme);jsEditor.setOption("theme", theme);}
function selectTheme(w){
  var prvcmtheme=htmlEditor.getOption("theme"),nt,ot,h=document.getElementsByTagName('head')[0];
  var theme = cmthemesel.options[cmthemesel.selectedIndex].innerHTML;
  ot = document.getElementsByTagName('link');
  for(var k=ot.length;k>=0;k--){
    if(ot[k] && ot[k].getAttribute('href')!==null && ot[k].getAttribute('href').indexOf('mine/theme/'+prvcmtheme+'.css')!=-1){
	  ot[k].parentNode.removeChild(ot[k]);
	}
  }
  nt = document.createElement("link");
  nt.setAttribute("rel","stylesheet");
  nt.setAttribute("type","text/css");
  if(w!=undefined){theme=w;}
  nt.setAttribute("href",'mine/theme/'+theme+'.css');
  if(typeof nt!="undefined"){
    h.appendChild(nt);
  }
  htmlEditor.setOption("theme", theme);cssEditor.setOption("theme", theme);jsEditor.setOption("theme", theme);
}

  
var cssEditor = CodeMirror.fromTextArea(document.getElementById("cssarea"),{
  mode:"css",lineNumbers:true,lineWrapping:true,dragDrop:true,matchBrackets:true,
  onChange:function(){if(refresh==1){clearTimeout(delay);delay=setTimeout(updateResult,300);}},
  extraKeys:{Tab:betterTab}
});
var cssCompletion = new CodeCompletion(cssEditor, new CssCompletion());
cssEditor.setOption("onKeyEvent", function(cm, e){return cssCompletion.handleKeyEvent(cm, e);});

function passAndHint(cm){setTimeout(function() {cm.execCommand("autocomplete");}, 100);return CodeMirror3.Pass;}
function myHint(cm){return CodeMirror3.showHint(cm, CodeMirror3.ternHint, {async: true});}
CodeMirror3.commands.autocomplete = function(cm){CodeMirror3.showHint(cm, myHint);}
var jsEditor = CodeMirror3.fromTextArea(document.getElementById("jsarea"), {
  mode: 'application/javascript',styleActiveLine:true,lineNumbers:true,lineWrapping:true,autoCloseBrackets:true,dragDrop:true,matchBrackets:true,
  extraKeys: {"'.'": passAndHint},
  gutters: ["CodeMirror3-lint-markers", "CodeMirror3-linenumbers"],
  lintWith: CodeMirror3.javascriptValidator,
  textHover: {delay:300},
  onKeyEvent: function (e, s) {
    if(s.type == "keyup" && ((s.keyCode >= 65 && s.keyCode <= 90) || s.keyCode == 190)){CodeMirror3.showHint(e, myHint);}
  }
});

jsEditor.on("change", function(){if(refresh==1){clearTimeout(delay);delay = setTimeout(updateResult, 300);}});
setTimeout(updateResult, 300);

function betterTab(cm){if (cm.somethingSelected()){cm.indentSelection("add");}else{cm.replaceSelection(cm.getOption("indentWithTabs")? "\t": Array(cm.getOption("indentUnit") + 1).join(" "), "end", "+input");}}
function scrollToBottom(){if (stickyScroll==1){$('#resultarea').contents().scrollTop($('#resultarea').contents().height());}else if(stickyScroll==0){$('#resultarea').contents().scrollTo(0, 0);}}
function init(){var bc=$('#main').attr('class');$('#bottom').find('em.'+bc).addClass('active');if(confeditortheme!=undefined&&confeditortheme!='default'){selectTheme(confeditortheme);}}
function refresh(){if(refresh===0){$('#refresh').hide();}else if(refresh==1){$('#refresh').show();}}
function updateResult(){var previewFrame = document.getElementById('resultarea');var preview =  previewFrame.contentDocument ||  previewFrame.contentWindow.document;preview.open();preview.write('<style type="text/css">'+cssEditor.getValue()+'</style>');preview.write(htmlEditor.getValue());preview.write('<scr'+'ipt>'+jsEditor.getValue()+'</scr'+'ipt>');preview.close();$('#resultarea').contents().find('a').click(function(event){event.preventDefault();});}	
function getSelectedRange() {return { from: htmlEditor.getCursor(true), to: htmlEditor.getCursor(false) };}
function autoFormatSelection() {var range = getSelectedRange();htmlEditor.autoFormatRange(range.from, range.to);}
function commentSelection(isComment){var range = getSelectedRange();htmlEditor.commentRange(isComment, range.from, range.to);}      
/* notification funcs */
function hintscroll(){var p=$('#hint p'),pw=p.outerWidth();hscroll=setInterval(function(){p.animate({textIndent:'100%'},0,function(){p.animate({textIndent:'-'+pw},(pw*(pw/2))-pw);});},(pw*(pw/2))-pw)+2;}
function rmsg(){clearInterval(hscroll);msg=['This box is for notification.','This box is for providing hints.','This box is for communicating with the users and let them know about your site.','This box is for providing info about your website.','This box is for guiding users.'];var i=Math.floor(5*Math.random()),p=$('#bottom #hint p'),h=$('#bottom #hint');p.text(msg[i]).stop().css({textIndent:0});if(p.css('height')>=h.css('height')){/*p.text('No msgs...');*/hintscroll();}}
function done(){window.clearTimeout(dt);window.clearTimeout(st);$('#done').removeClass('error tdownfull').addClass('success tupfull').fadeIn();smile();}
function sad(){st=window.setTimeout(function(){$('#done').attr('class','icon').addClass('error sad').fadeIn();rdone();},5000);} 
function smile(){st=window.setTimeout(function(){$('#done').attr('class','icon').addClass('success smile').fadeIn();rdone();},5000);}
function rdone(){dt=window.setTimeout(function(){$('#done').fadeOut().attr('class','icon');},5000);}
function notdone(msg,y){var wm=$('#wmsg');window.clearTimeout(dt);window.clearTimeout(st);$('#done').attr('class','icon').addClass('error tdownfull').fadeIn();$('#warning').fadeIn();sad();if($('body').find('#wmsg').length>0){if(wm.find('li[data-for='+y+']').length>0){var prv=wm.find('li[data-for='+y+']'),t;t=prv.find('span').text(),count=prv.attr('data-count');ec=parseInt(count)+1;prv.remove();wm.prepend('<li data-for="'+y+'" data-count="'+ec+'"><i class="count">'+ec+'</i><span>'+t+'</span><i class="howtoresolve icon info"></i><i class="close icon remove"></i></li>');}else{wm.prepend('<li data-for="'+y+'" data-count="1"><span>'+msg+'</span><i class="howtoresolve icon info"></i><i class="close icon remove"></i></li>');}}else{$('<ul id="wmsg"><li data-for="'+y+'" data-count="1"><span>'+msg+'</span><i class="howtoresolve icon info"></i><i class="close icon remove"></i></li></ul>').appendTo('body');}}
function infomarquee(t){imr=0;var i=$('#hvthinfo');i.append(marquee).addClass('error');i.find('#marquee').text(t);setTimeout(function(){i.removeClass('error');i.find('#marquee').empty().remove();imr=1;},30000);}
/* dynamically add code css/js */
function dynaadd(o){var css = o.css, js = o.js, jc = 0, ct, jt, h = document.getElementsByTagName('head')[0], cb = o.callback;for(var i in css){ct = document.createElement("link");ct.setAttribute("rel","stylesheet");ct.setAttribute("type","text/css");ct.setAttribute("href",css[i]);if(typeof ct!="undefined"){h.appendChild(ct);}}for(var i in js){jt = document.createElement("script");jt.setAttribute("type","text/javascript");/*if(typeof cb == "function"){if(jt.readyState){jt.onreadystatechange = function(){if(jt.readyState == "loaded" || jt.readyState == "complete"){jc++;if(jc == js.length){cb.call();}}}}else{jt.onload = function(){jc++;if(jc == js.length){cb.call();}}}}*/jt.setAttribute("src",js[i]);if(typeof jt!="undefined"){h.appendChild(jt);}}}
function dynarmv(o){var css = o.css, js = o.js, ct, jt, cb = o.callback;for(var i in css){ct = document.getElementsByTagName('link');for(var k=ct.length;k>=0;k--){if(ct[k] && ct[k].getAttribute('href')!==null && ct[k].getAttribute('href').indexOf(css[i])!=-1){ct[k].parentNode.removeChild(ct[k]);}}}for(var i in js){jt = document.getElementsByTagName('script');for(var k=jt.length;k>=0;k--){if(jt[k] && jt[k].getAttribute('src')!==null && jt[k].getAttribute('src').indexOf(js[i])!=-1){jt[k].parentNode.removeChild(jt[k]);}}}}
/* adding css/js/meta/ie */
function addjslib(url){var ns=jssyntax.replace('src=""','src="'+url+'"'),hv=htmlEditor.getValue(),he=hv.search('</head>'),ht=hv.search('</html>'),t=hv.search('</title>'),ss=hv.search(url),nval='';if(ss>0){return false;}else{if(he>0){if(t>0){nval=hv.replace('</title>','</title>'+'\n'+ns);}else{nval=hv.replace('<head>','<head>'+'\n'+'<title>Your title here</title>'+'\n'+ns);}}else if(ht>0){nval=hv.replace('<html>','<html>'+'\n'+'<head>'+'\n'+'<title>Your title here</title>'+'\n'+ns+'\n'+'</head>');}else if(hv!==''){nval='<html>'+'\n'+'<head>'+'\n'+'<title>Your title here</title>'+'\n'+ns+'</head>'+hv+'</html>';}else if(hv===''){nval='<html>'+'\n'+'<head>'+'\n'+'<title>Your title here</title>'+'\n'+ns+'\n'+'</head>'+'\n'+'<body>'+'\n'+'</body>'+'\n'+'</html>';}htmlEditor.setValue(nval);done();}}
function addcsslib(url){var ns=csssyntax.replace('href=""','href="'+url+'"'),hv=htmlEditor.getValue(),he=hv.search('</head>'),ht=hv.search('</html>'),t=hv.search('</title>'),ss=hv.search(url),nval='';if(ss>0){return false;}else{if(he>0){if(t>0){nval=hv.replace('</title>','</title>'+'\n'+ns);}else{nval=hv.replave('<head>','<head>'+'\n'+'<title>Your title here</title>'+'\n'+ns);}}else if(ht>0){nval=hv.replace('<html>','<html>'+'\n'+'<head>'+'\n'+'<title>Your title here</title>'+'\n'+ns+'\n'+'</head>');}else if(hv!==''){nval='<html>'+'\n'+'<head>'+'\n'+'<title>Your title here</title>'+'\n'+ns+'</head>'+hv+'</html>';}else if(hv===''){nval='<html>'+'\n'+'<head>'+'\n'+'<title>Your title here</title>'+'\n'+ns+'\n'+'</head>'+'\n'+'<body>'+'\n'+'</body>'+'\n'+'</html>';}htmlEditor.setValue(nval);done();}}
function addie(con){var hv=htmlEditor.getValue(),he=hv.search('</head>'),ht=hv.search('</html>'),nval='';var s1=con.split('<').join(''),s2=s1.split('>').join(''),s3=s2.split('!').join(''),s4=s3.split('[').join(''),s5=s4.split(']').join(''),s6=s5.split('-').join(''),s7=s6.split('endif').join(''),ss=hv.search(s7);if(ss>=0){return false;}else{if(he>0){nval=hv.replace('</head>',con+'\n'+'</head>');}else if(ht>0){nval=hv.replace('<html>','<html>'+'\n'+'<head>'+'\n'+'<title>Your title here</title>'+'\n'+con+'\n'+'</head>'+'\n'+hv+'\n'+'</html>');}else if(hv!==''){nval='<html>'+'\n'+'<head>'+'\n'+'<title>Your title here</title>'+'\n'+con+'\n'+'</head>'+'\n'+hv+'\n'+'</html>';}else if(hv===''){nval='<html>'+'\n'+'<head>'+'\n'+'<title>Your title here</title>'+'\n'+con+'\n'+'</head>'+'\n'+'<body>'+hv+'\n'+'</body>'+'\n'+'</html>';}htmlEditor.setValue(nval);done();}}
function addmeta(type){var hv=htmlEditor.getValue(),he=hv.search('</head>'),ht=hv.search('</html>'),t=hv.search('</title>'),ss=hv.search(type),nval='';if(ss>0){return false;}else{if(t>0){nval=hv.replace('</title>','</title>'+'\n'+type);}else if(he>0){nval=hv.replace('<head>','<head>'+'\n'+'<title>Your title here</title>'+'\n'+type);}else if(ht>0){nval=hv.replace('<html>','<html>'+'\n'+'<head>'+'\n'+'<title>Yout title here</title>'+'\n'+type+'\n'+'</head>');}else if(hv!==''){nval='<html>'+'\n'+'<head>'+'\n'+'<title>Your title here</title>'+'\n'+type+'\n'+'</head>'+'\n'+hv+'\n'+'</html>';}else if(hv===''){nval='<html>'+'\n'+'<head>'+'\n'+'<title>Your title here</title>'+'\n'+type+'\n'+'</head>'+'\n'+'<body>'+'\n'+'</body>'+'\n'+'</html>';}htmlEditor.setValue(nval);done();}}
function headclose(c){var hv=htmlEditor.getValue(),he=hv.search('</head>'),ht=hv.search('</html>'),t=hv.search('</title>'),ss=hv.search(c),nval='';if(ss>0){return false;}else{if(he>0){nval=hv.replace('</head>',c+'\n'+'</head>');}else if(t>0){nval=hv.replace('</title>','</title>'+'\n'+c);}else if(ht>0){nval=hv.replace('<html>','<html>'+'\n'+'<head>'+'\n'+'<title>Your title here</title>'+'\n'+c+'\n'+'</head>');}else if(hv!==''){nval='<html>'+'\n'+'<head>'+'\n'+'<title>Your title here</title>'+'\n'+c+'</head>'+hv+'</html>';}else if(hv===''){nval='<html>'+'\n'+'<head>'+'\n'+'<title>Your title here</title>'+'\n'+c+'\n'+'</head>'+'\n'+'<body>'+'\n'+'</body>'+'\n'+'</html>';}htmlEditor.setValue(nval);done();}}
/* preview */
function getcode(){
  var html=htmlEditor.getValue(),css=cssEditor.getValue(),js=jsEditor.getValue(),src='';
  src=base.replace('</body>',html+'</body>');
  css='<style type="text/css">'+css+'</style>'+'\n';
  src=src.replace('</head>',css+'</head>');
  js='\n'+'<script type="text/javascript">'+js+'<\/script>';
  src=src.replace('</body>','</body>'+js);
  return src;
}
/* core func */
function clearreset(which){var gc=cssEditor.getValue(),s='';if(which=='eric'){ericreset=1;s=gc.replace(eric,eric);}else{normreset=1;s=gc.replace(normalize,normalize);}done();cssEditor.setValue(s);$('body').find('#modal').find('#ac').remove();$('#modal').fadeOut();}
function optionserror(val,t){if(!t){t='error';}window.clearTimeout(oetime);if($('#optionserror').length>0){$('#optionserror').empty().text(val);}else{$('#options').prepend('<p id="optionserror" style="width:100%;text-align:center;font-size:10px;margin-bottom:10px;">'+val+'</p>');}if(t=='error'){$('#optionserror').css({color:'#a60000'});}else if(t=='info'){$('#optionserror').css({color:'#ffb773'});}else{$('#optionserror').css({color:'#007439'});}oetime=window.setTimeout(function(){$('#optionserror').fadeOut();},5000);}
function compresshtml(){var e=htmlEditor.getValue();if(e==''){notdone('Nothing for compression','herror');optionserror('BLANK/NO DATA TO COMPRESS');}else{var t="";var n="";var r=document.getElementById("headornot").checked;if(r!==true){e=e.replace(/(\r\n|\n|\r|\t)/gm,"");e=e.replace(/\s+/g," ");}else{e=e.replace(new RegExp("</HEAD","gi"),"</head");e=e.replace(new RegExp("</head ","gi"),"</head");var i="</head>";var s=e.indexOf(i)!=-1;if(s===true){i="</head>";tempo=e.split(new RegExp(i,"i"));t=tempo[0];e=tempo[1];}else{i="";}e=e.replace(/(\r\n|\n|\r|\t)/gm,"");e=e.replace(/\s+/g," ");e=t+i+"\n"+e;}htmlEditor.setValue(e);done();optionserror('Done!!','success');}}
function enchtmlgenerate(){code=htmlEditor.getValue();if(code){if(get(enchtmlreset)===undefined){set(enchtmlreset,code);}optionserror('Compiling...Please wait!','info');setTimeout(enchtmlcompile(),1000);}else{optionserror('BLANK/NO DATA TO COMPRESS');}$('#close,#cancel').click(function(){set(enchtmlreset,'');});}
function enchtmlcompile(){compilation=escape(code);nval="<script>\n<!--\ndocument.write(unescape(\""+compilation+"\"));\n//-->\n<\/script>";htmlEditor.setValue(nval);done();optionserror('Compilation Done!!','success');$('#enchtmlreset,#enchtmlpreview,#enchtmlsource').fadeIn();$(window).resize();}
function enchtmlpreview(){var he=htmlEditor.getValue();if(he.length>0){pr=window.open("","Preview","scrollbars=1,menubar=1,status=1,width=700,height=320,left=50,top=110");pr.document.write(he);}else{notdone('Nothing for preview in HTML area','herror');optionserror('Nothing for be previewed!');}}
function enchtmluncompile(){var he=htmlEditor.getValue();if (he.length>0){source=unescape(he);nval=""+source+"";htmlEditor.setValue(nval);done();}else{optionserror('You need compiled code to uncompile it!');}}
function enchtmlreset(){var ej=get(enchtmlreset);htmlEditor.setValue(ej);done();$('#enchtmlreset,#enchtmlpreview,#enchtmlsource').fadeOut();$(window).resize();optionserror('RESET Done!!','success');}
function get(ele){return ele.value;}function set(ele,val){ele.value=val;}
function h2jpreview(){var he=htmlEditor.getValue();if(he===''){notdone('Nothing for preview in HTML area','herror');optionserror('NOTHING FOR PREVIEW');}else{var pWin= window.open("","PreviewWin");pWin.document.write(he);return true;}}
/* function h2jconvert(){var r=htmlEditor.getValue();var strVar=$("#h2jvarname").val();if(strVar==""){strVar="strVar";}var g="";var arr=r.split("\n");var opt=$("input[name='html2js']:checked").attr("id");if(opt=="h2jstatement"){g+="<script type=\"text\/javascript\">\n";g+="function HTML2JS(){\n";};if(opt=="h2jvar"){g+="var "+strVar+"=\"\";\n";};for(i=0;i<arr.length;i++){var l="";if((opt=="h2jseries")||(opt=="h2jstatement")){l+="document.write(\"";};if(opt=="h2jvar"){l+=strVar+" += \"";};l+=arr[i].replace(/\"/g,"\\\"").replace(/\//g,"\\/");if((opt=="h2jseries")||(opt=="h2jstatement")) {l += "\");";};if(opt=="h2jvar"){l+="\";";};l += "\n";g += l;}if(opt=="h2jstatement"){g+="}\n";g+="<\/script>";g += "\n\n<!--\nnow place this function call at whatever point\nit needs to write the markup on to the page: -->\n\n";g+="<script type=\"text\/javascript\">\n";g+="HTML2JS();\n";g+="<\/script>";};set(h2jconverted,r);} */
function h2jconvert(){var r=htmlEditor.getValue();if(r===''){notdone('Nothing for preview in HTML area','herror');optionserror('BLANK/NO DATA TO CONVERT');}else{if(get(h2jconverted)===''){set(h2jconverted,r);}r=get(h2jconverted);var strVar=$("#h2jvarname").val();if(strVar===""){strVar="strVar";}var g="";var arr=r.split("\n");var opt=$("input[name='html2js']:checked").attr("id");if(opt=="h2jstatement"){g+="<script type=\"text\/javascript\">\n";g+="function HTML2JS(){\n";}if(opt=="h2jvar"){g+="var "+strVar+"=\"\";\n";}for(i=0;i<arr.length;i++){var l="";if((opt=="h2jseries")||(opt=="h2jstatement")){l+="document.write(\"";}if(opt=="h2jvar"){l+=strVar+" += \"";}l+=arr[i].replace(/\"/g,"\\\"").replace(/\//g,"\\/");if((opt=="h2jseries")||(opt=="h2jstatement")){l+= "\");";}if(opt=="h2jvar"){l+="\";";}l += "\n";g+= l;}if(opt=="h2jstatement"){g+="}\n";g+="<\/script>";g+= "\n\n<!--\nnow place this function call at whatever point\nit needs to write the markup on to the page: -->\n\n";g+="<script type=\"text\/javascript\">\n";g+="HTML2JS();\n";g+="<\/script>";}htmlEditor.setValue(g);done();optionserror('HTMLtoJS Conversion Done!!','success');$('#h2jreset,#h2jpreview').fadeIn();$(window).resize();$('#close,#cancel').click(function(){set(h2jconverted,'');});}}
function h2jreset(){var cj=get(h2jconverted);htmlEditor.setValue(cj);optionserror('RESET Done!!','success');done();$('#h2jreset,#h2jpreview').fadeOut();$(window).resize();}
function compresscss(){var sa=document.getElementById("stripAllComment"),sc=document.getElementById("superCompact"),bi=document.getElementById("betterIndentation"),n=/@(media|-w|-m|-o|keyframes|page)(.*?)\{([\s\S]+?)?\}\}/ig,r=cssEditor.getValue(),i=r.length;if(r===''){notdone('Nothing to compress in CSS area','cerror');optionserror('BLANK/NO DATA TO COMPRESS');}else{r=sa.checked||sc.checked?r.replace(/\/\*[\w\W]*?\*\//gm,""):r.replace(/(\n+)?(\/\*[\w\W]*?\*\/)(\n+)?/gm,"\n$2\n");r=r.replace(/([\n\r\t\s ]+)?([\,\:\;\{\}]+?)([\n\r\t\s ]+)?/g,"$2");r=sc.checked?r:r.replace(/\}(?!\})/g,"}\n");r=bi.checked?r.replace(n,function(e){return e.replace(/\n+/g,"\n  ");}):r.replace(n,function(e){return e.replace(/\n+/g,"");});r=bi.checked&&!sc.checked?r.replace(/\}\}/g,"}\n}"):r;r=bi.checked&&!sc.checked?r.replace(/@(media|-w|-m|-o|keyframes)(.*?)\{/g,"@$1$2{\n  "):r;r=r.replace(/;\}/g,"}");r=r.replace(/\:0(px|em|pt)/ig,":0");r=r.replace(/ 0(px|em|pt)/ig," 0");r=r.replace(/\s+\!important/ig,"!important");r=r.replace(/(^\n+|\n+$)/,"");cssEditor.setValue(r);done();optionserror('CSS Compression Done!!','success');}}
function beautifycss(){var sa=document.getElementById("stripAllComment"),sc=document.getElementById("superCompact"),bi=document.getElementById("betterIndentation"),bs=document.getElementById("breakSelector"),tt=document.getElementById("toTab"),to=document.getElementById("tabOpt").getElementsByTagName("input"),sb=document.getElementById("spaceBetween"),ip=document.getElementById("inlineSingleProp"),rs=document.getElementById("removeLastSemicolon"),il=document.getElementById("inlineLayout"),si=document.getElementById("singleBreak");sc.checked=false;sa.checked=false;bi.checked=false;compresscss();var n=/\n@(media|-w|-m|-o|keyframes|page)(.*?)\{([\s\S]+?)?\}\n\}/ig,r=cssEditor.getValue();if(r===''){notdone('Nothing to beautify in CSS area','cerror');optionserror('BLANK/NO DATA TO BEAUTIFY');}else{if(!il.checked){r=r.split(";").join(";\n  ");r=r.split("{").join(" {\n  ");r=r.split("}").join(";\n}\n");r=r.replace(/\}([\n\s;]+?)?\}/g,"}\n}");r=bs.checked?r.replace(/\n(.*?)\{/g,function(e){return e.replace(/,/g,",\n");}):r;r=r.replace(/@([\s\S]+?)\{/g,function(e){return e.replace(/,\n/g,", ");});r=r.replace(n,function(e){return e.replace(/\n/g,"\n  ").replace(/\n\s+\n/g,"\n").replace(/\}\n+\s+\}/g,"}\n}");});}else{r=r.replace(/;/g,"; ");r=r.replace(/\{(.*?)\}/g," { $1; }");r=r.replace(/\}\}/g,"}\n}");r=r.replace(n,function(e){return e.replace(/\n/g,"\n    ").replace(/\n+\s+\n/g,"\n").replace(/\}\n\s+\}/g,"}\n}");});r=r.replace(/\{(.*?)\{(.*?):(.*?)\}\n/g,"{\n     $1 { $2:$3}\n");}r=r.replace(/\{\n  ;\n\}|\{ ; \}/g,"{}");r=sb.checked?r.replace(/\{([\s\S]+?)\}|\((.*?)\)/gm,function(e){return e.replace(/(,|\:)/g,"$1 ");}):r;r=sb.checked?r.replace(/(.*?)\{/g,function(e){return e.replace(/,/g,", ");}):r;r=r.replace(/\!important/g," !important");r=r.replace(/data: ?image(.*?);([\n\r\t\s]+)base64, ?/g,"data:image$1;base64,");r=r.replace(/\n\s+@(.*?)\{\n    /g,"\n\n@$1{\n  ");r=ip.checked?r.replace(/(.*){(\n\s+|\t)(.*)\:(.*);\n(\s+)?}/g,"$1{$3:$4;}"):r;r=rs.checked?r.replace(/\{(.*?)\;(\s+)?\}/g,"{$1$2}"):r;r=tt.checked&&to[0].checked?r.split(/  /).join("	"):r;r=tt.checked&&to[1].checked?r.split(/  /).join("    "):r;r=il.checked?r.replace(n,function(e){return e.replace(/\}/g,"} ");}):r;r=si.checked?r.replace(/(\}|\*\/)\n+/g,"$1\n").replace(/\/\*/g,"\n/*"):r.replace(/\*\/\n(.)/g,"*/\n\n$1");r=r.replace(/(^\n+|\n+$)/,"");bs.disabled=il.checked?true:false;ip.disabled=il.checked?true:false;tt.disabled=il.checked?true:false;to[0].disabled=tt.checked&&!il.checked?false:true;to[1].disabled=tt.checked&&!il.checked?false:true;cssEditor.setValue(r);done();optionserror('CSS Beautification Done!!','success');}}
/* compress js  start */
String.prototype.has=function(c){return this.indexOf(c)>-1;};
function cjscompile(input,level){var cjs=get(cjsreset);if(cjs===''||cjs===undefined){set(cjsreset,input);}else{input=get(cjsreset)};if(level===undefined||level<1||level>3){level=2;}if(input.length>0){input+='\n';}var a='',b='',EOF=-1,LETTERS='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz',DIGITS='0123456789',ALNUM=LETTERS+DIGITS+'_ i\\',theLookahead=EOF;function isAlphanum(c){return c!=EOF&&(ALNUM.has(c)||c.charCodeAt(0)>126);}var iChar=0,lInput=input.length;function getc(){var c=theLookahead;if(iChar==lInput){return EOF;}theLookahead=EOF;if(c==EOF){c=input.charAt(iChar);++iChar;}if(c>=' '||c=='\n'){return c;}if(c=='\r'){return'\n';}return' ';}function getcIC(){var c=theLookahead;if(iChar==lInput){return EOF;}theLookahead=EOF;if(c==EOF){c=input.charAt(iChar);++iChar;}if(c>=' '||c=='\n'||c=='\r'){return c;}return' ';}function peek(){theLookahead=getc();return theLookahead;}function next(){var c=getc();if(c=='/'){switch(peek()){case'/':for(;;){c=getc();if(c<='\n'){return c;}}break;case'*':getc();if(peek()=='!'){getc();var d='/*!';for(;;){c=getcIC();switch(c){case'*':if(peek()=='/'){getc();return d+'*/';}break;case EOF:throw'Error: Unterminated cjsreset.';default:d+=c;}}}else{for(;;){switch(getc()){case'*':if(peek()=='/'){getc();return' ';}break;case EOF:throw'Error: Unterminated cjsreset.';}}}break;default:return c;}}return c;}function action(d){var r=[];if(d==1){r.push(a);}if(d<3){a=b;if(a=='\''||a=='"'){for(;;){r.push(a);a=getc();if(a==b){break;}if(a<='\n'){throw'Error: unterminated string literal: '+a;}if(a=='\\'){r.push(a);a=getc();}}}}b=next();if(b=='/'&&'(,=:[!&|'.has(a)){r.push(a);r.push(b);for(;;){a=getc();if(a=='/'){break;}else if(a=='\\'){r.push(a);a=getc();}else if(a<='\n'){throw'Error: unterminated Regular Expression literal';}r.push(a);}b=next();}return r.join('');}function m(){var r=[];a='\n';r.push(action(3));while(a!=EOF){switch(a){case' ':if(isAlphanum(b)){r.push(action(1));}else{r.push(action(2));}break;case'\n':switch(b){case'{':case'[':case'(':case'+':case'-':r.push(action(1));break;case' ':r.push(action(3));break;default:if(isAlphanum(b)){r.push(action(1));}else{if(level==1&&b!='\n'){r.push(action(1));}else{r.push(action(2));}}}break;default:switch(b){case' ':if(isAlphanum(a)){r.push(action(1));break;}r.push(action(3));break;case'\n':if(level==1&&a!='\n'){r.push(action(1));}else{switch(a){case'}':case']':case')':case'+':case'-':case'"':case'\'':if(level==3){r.push(action(3));}else{r.push(action(1));}break;default:if(isAlphanum(a)){r.push(action(1));}else{r.push(action(3));}}}break;default:r.push(action(1));break;}}}return r.join('');}cjscompile.oldSize=input.length;ret=m(input);cjscompile.newSize=ret.length;return ret;}
function compressjs(){var js=jsEditor.getValue();if(js===''){optionserror('BLANK/NO DATA TO COMPRESS');}else{var type=document.getElementById('cjslevel');type=type.options[type.selectedIndex].value;var jsc=cjscompile(jsEditor.getValue(),type);jsEditor.setValue(jsc);$('#cjsstats,#cjsreset').fadeIn();$('#cjsoldsize').val(cjscompile.oldSize);optionserror('JS Compression Done','success');$('#cjsnewsize').val(cjscompile.newSize);$('#cjsratio').val((Math.round(cjscompile.newSize/cjscompile.oldSize*1000)/10)+'%');}}
function cjsreset(){var cj=get(cjsreset);jsEditor.setValue(cj);$('#cjsreset').fadeOut();optionserror('RESET Done!!','success');set(cjsreset,'');}
/* compress js end */
function sample(w){var h='<!-- PRESS "CTRL+SPACE" FOR HELP AFTER ENTERING 1ST CHAR/VAR/TAG //-->'+'\n\n'+'<!doctype html>'+'\n'+'<html>'+'\n'+'<head>'+'\n'+'<title>Your title here</title>'+'\n\n'+'<!-- META contents goes here //-->'+'\n'+'<!-- JS/CSS contents goes here //-->'+'\n'+'<!-- FAVICON or any additional TAGS can be placed here //-->'+'\n\n'+'</head>'+'\n'+'<body>'+'\n'+'<!-- Your content starts from here //-->'+'\n\n'+'<p>This is a paragraph</p>'+'\n\n'+'<!-- Content end here //-->'+'\n'+'</body>'+'\n\n'+'<!-- JS can be placed here for better optimization/speed //-->'+'\n\n'+'</html>',c='/* Styling your WebPage */'+'\n'+'p{color:#333;background-color:#fff;}',j='/* PRESS "CTRL+SPACE" FOR AUTOCOMPLETE/HELP */'+'\n\n'+'/* Your JS content goes here */'+'\n'+'function add(){'+'\n'+'var a=1,b=1,c=a+b;'+'\n'+'return c;'+'\n'+'}'+'\n';if(w=='html'){htmlEditor.setValue(h);}else if(w=='css'){cssEditor.setValue(c);}else if(w=='js'){jsEditor.setValue(j);}else{htmlEditor.setValue(h);cssEditor.setValue(c);jsEditor.setValue(j);}done();$('#cancel').click();}
/* cookie */
function store(name,value,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires="; expires="+date.toGMTString();}else var expires="";document.cookie=name+"="+value+expires+"; path=/";}
function read(name){var nameEQ=name+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1,c.length);if(c.indexOf(nameEQ)==0)return c.substring(nameEQ.length,c.length);}return null;}
function erase(name){store(name,"",-1);}
/* lock/unlock */
function unlock(){}
function lock(){}
function savelock(){}
function nolock(){modal('Enter Code','Dear Visitor, to lock the code spinnet, firstly you must enter the CODE.<div id="options"><input type="password" id="code1" placeholder="Enter Code"/><input type="password" id="code2" placeholder="Re-Enter Code" /><hr/><i class="ok icon" onclick="savelock();">Save Code</i></div>');}
/* modal */
function modal(t,i,c){var b=$('body'),w=$(window),tit='#title',m='#modal',mi='#modalinner',o='#options';
  if(b.find(m).length<=0){b.append(mod);}b.find(tit).empty().text(t);b.find(mi).empty().append(i);b.find(o).find('#run').css('display','block');if(!c){b.find(o).append(cancel);}w.resize();
  var radio=$('#modal input[type="radio"]'),checkbox=$('#modal input[type="checkbox"]');radio.addClass('radio');radio.next('label').addClass('labelr');checkbox.addClass('checkbox');checkbox.next('label').addClass('labelc');
  b.find(m).fadeIn();
}

function howtoresolve(y){
var yinfo='';
if(y=='head'){
  yinfo='Enter "<head>" after the opening "<html>" OR "<!doctype html>" tag.'+'\n'+'And don'+"'"+'t forget to close this "<head>" tag with "</head>"';
}else if(y=='html'){
  yinfo='Put "<html>" on the starting of your webpage and place "</html>" at the bottom. All your content must be within these tags.';
}else if(y=='title'){
  yinfo='<title> tag must be placed after the opening "<head>" tag. Like'+'\n\t'+'<head>'+'\n\t\t'+'<title>DEMO TITLE</title>'+'\n\t'+'</head>';
}else if(y=='body'){
  yinfo='BODY tag must be placed after the closing HEAD tag. Like'+'\n\t'+'</head>'+'\n'+'<body>'+'\n\t\t'+'YOUR CONTENTS'+'</body>';
}else if(y=='styletag'){
  yinfo='You must put your STYLESHEET tag between the opening and closing HEAD tags. Like'+'\n\t'+'<head>'+'\n\t\t'+'<style type="text/css">YOUR STYLING CLASSES OR IDs</style>'+'\n\t'+'</head>';
}else if(y=='preview'){
  yinfo='For a webpage, there must be few HTML lines is necessary and if there is no such line, than may be it is based on JAVASCRIPT. So for previewing, please make your coding first.'+'\n'+'You can also use our MAGIC {from the MAGIC icon on the topbar} to get the default coding for all areas';
}else if(y=='herror'){
  yinfo='You must enter something into the HTML area and convert/encryt it before previewing. You can also use the MAGIC icon from the top for automatic setting the DEFAULT/SAMPLE code for all areas';
}else if(y=='jerror'){
  yinfo='You must enter something into the JS area for compression. You can also use the MAGIC icon from the top for automatic setting the DEFAULT/SAMPLE code for all areas';
}else if(y=='cerror'){
  yinfo='You must enter something into the CSS area for compression/beautifier. You can also use the MAGIC icon from the top for automatic setting the DEFAULT/SAMPLE code for all areas';
}else{
  yinfo='I'+"'"+'m sorry because I can'+"'"+'t handel this error in a specific manner. Please try GOOGLING :)';
}return yinfo;
}
function runcsslib(){
  var type=document.getElementById('taboption'),w=$(window);
  type=type.options[type.selectedIndex].value;
  var gcss=cssEditor.getValue();var ucss;
  if(normreset==1&&ericreset==1){if(type=='eric'){ucss=eric+'\n\n'+gcss;ericreset=0;}else if(type=='normalize'){ucss=normalize+'\n\n'+gcss;normreset=0;}cssEditor.setValue(ucss);done();$('#modal').fadeOut();}else{var which;if(ericreset=0){which="Eric's";}else{which="Normalize";}$('#options').find('#run').css('display','none');$('#options').find('p').remove();$('#options').prepend('<p id="ac" style="color:#000;margin-top:10px;font-size:11px;">You already used the '+which+' reset.Please use clear option to use another. <i id="clearreset">CLEAR</i></p>');w.resize();}
}

function refreshcm(){cssEditor.refresh();htmlEditor.refresh();jsEditor.refresh();}

var resize=function(){
  rmsg();refreshcm();
  var width=-1*parseInt(($('#modal').width()/2));
  var height=-1*parseInt(($('#modal').height()/2));
  $('#modal').css('margin-left',width).css('margin-top',height);
  //var topPos=($(window).height()-$('#modal').outerHeight())/2;$('#modal').css({left:($(window).width()-$('#modal').outerWidth())/2,top:topPos>0?topPos:0});
};
$(window).resize(resize);$(window).resize();